import Head from "next/head";
import React from "react";

export default () => (
  <Head>
    <title>Roulette</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);
